brew 'git'
brew 'bash'
brew 'tmux'
brew 'imagemagick'
brew 'wget'
brew 'the_silver_searcher'
brew 'ctags'
brew 'reattach-to-user-namespace', args: ['with-wrap-pbcopy-and-pbpaste']

cask 'iterm2'
cask 'gimp'
