brew 'git'
brew 'bash'
brew 'bash-completion'
brew 'tmux'
brew 'imagemagick'
brew 'wget'
brew 'gnu-sed'
brew 'the_silver_searcher'
brew 'ctags'
brew 'reattach-to-user-namespace', args: ['with-wrap-pbcopy-and-pbpaste']
brew 'shellcheck'
brew 'go', args: ['cross-compile-common']
brew 'graphviz'


cask 'iterm2'
cask 'gimp'
cask 'google-chrome'
cask 'opera'
cask 'skype'
cask 'dash'
cask 'visual-studio-code'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'

